<?php require_once "includes/header.php" ?>

<div class="content" id="blog">



	
<div id="post-1435" class="content container-main py-5 entry post-1435 post type-post status-publish format-standard hentry category-particle-physics">

	<h2>Miracles when you use the right&nbsp;metric</h2>

	<p>I recommend reading, <em>carefully and thoughtfully</em>, the preprint &#8220;The Metric Space of Collider Events&#8221; by Patrick Komiske, Eric Metodiev, and Jesse Thaler (<a href="http://arxiv.org/abs/1902.02346" rel="noopener noreferrer" target="_blank">arXiv:1902.02346</a>).  There is a lot here, perhaps somewhat cryptically presented, but much of it is exciting.</p>
<p>First, you have to understand what the <a href="https://en.wikipedia.org/wiki/Earth_mover%27s_distance" rel="noopener noreferrer" target="_blank">Earth Mover&#8217;s Distance</a> (EMD) is.   This is easier to understand than the <a href="https://en.wikipedia.org/wiki/Wasserstein_metric" rel="noopener noreferrer" target="_blank">Wasserstein Metric</a> of which it is a special case.  The EMD is a measure of how different two pdfs (probability density functions) are and it is rather different than the usual chi-squared or mean integrated squared error because it emphasizes separation rather than overlap.  The idea is look at how much work you have to do to reconstruct one pdf from another, where &#8220;reconstruct&#8221; means transporting a portion of the first pdf a given distance.  You keep track of the &#8220;work&#8221; you do, which means the amount of area (i.e.,&#8221;energy&#8221; or &#8220;mass&#8221;) you transport and how far you transport it.  The <a href="https://en.wikipedia.org/wiki/Earth_mover%27s_distance" rel="noopener noreferrer" target="_blank">Wikipedia article</a> aptly makes an analogy with suppliers delivering piles of stones to customers.  The EMD is the smallest effort required.</p>
<p>The EMD is a rich concept because it allows you to carefully define what &#8220;distance&#8221; means.  In the context of delivering stones, transporting them across a plain and up a mountain are not the same.  In this sense, rotating a collision event about the beam axis should &#8220;cost&#8221; nothing &#8211; i.e, be irrelevant &#8212; while increasing the energy or transverse momentum should, because it is phenomenologically interesting.  </p>
<p>The authors want to define a metric for LHC collision events with the notion that events that come from different processes would be well separated.  This requires a definition of &#8220;distance&#8221; &#8211; hence the word &#8220;metric&#8221; in the title.  You have to imagine taking one collision event consisting of individual particle or perhaps a set of hadronic jets, and transporting pieces of it in order to match some other event.  If you have to transport the pieces a great distance, then the events are very different.   The authors&#8217; ansatz is a straight forward one, depending essentially on the angular distance &theta;<sub>ij</sub>/R plus a term than takes into account the difference in total energies of the two events.  Note: the subscripts i and j refer to two elements from the two different events.  The paper gives a very nice illustration for two top quark events (read and blue):<br />
<div data-shortcode="caption" id="attachment_1437" style="width: 297px" class="wp-caption aligncenter"><img aria-describedby="caption-attachment-1437" data-attachment-id="1437" data-permalink="https://muon.wordpress.com/2019/02/24/miracles-when-you-use-the-right-metric/emdexample_top_0/" data-orig-file="https://muon.files.wordpress.com/2019/02/emdexample_top_0.png" data-orig-size="287,281" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="EMDExample_Top_0" data-image-description="" data-image-caption="&lt;p&gt;Transformation of one top quark event into another&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2019/02/emdexample_top_0.png?w=287" data-large-file="https://muon.files.wordpress.com/2019/02/emdexample_top_0.png?w=287" src="https://muon.files.wordpress.com/2019/02/emdexample_top_0.png?w=455" alt=""   class="size-full wp-image-1437" srcset="https://muon.files.wordpress.com/2019/02/emdexample_top_0.png 287w, https://muon.files.wordpress.com/2019/02/emdexample_top_0.png?w=150 150w" sizes="(max-width: 287px) 100vw, 287px" /><p id="caption-attachment-1437" class="wp-caption-text">Transformation of one top quark event into another</p></div></p>
<p>The first thing that came to mind when I had grasped, with some effort, the suggested metric, was that this could be a great classification tool.  And indeed it is.  The authors show that a k-nearest neighbors algorithm (KNN), straight out of the box, equipped with their notion of distance, <em>works nearly as well as very fancy machine learning techniques</em>!   It is crucial to note that there is no training here, no search for a global minimum of some very complicated objection function.   You only have to evaluate the EMD, and in their case, this is not so hard.   (Sometimes it is.)  Here are the ROC curves:<br />
<div data-shortcode="caption" id="attachment_1440" style="width: 287px" class="wp-caption aligncenter"><img aria-describedby="caption-attachment-1440" data-attachment-id="1440" data-permalink="https://muon.wordpress.com/2019/02/24/miracles-when-you-use-the-right-metric/roc-curve_w-qcd/" data-orig-file="https://muon.files.wordpress.com/2019/02/roc-curve_w-qcd.png" data-orig-size="277,264" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="ROC-Curve_W-QCD" data-image-description="" data-image-caption="&lt;p&gt;ROC curves.  The red curve is the KNN with this metric, and the other curves close by are fancy ML algorithms.  The light blue curve is a simple cut on N-subjettiness observables, itself an important theoretical tool&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2019/02/roc-curve_w-qcd.png?w=277" data-large-file="https://muon.files.wordpress.com/2019/02/roc-curve_w-qcd.png?w=277" src="https://muon.files.wordpress.com/2019/02/roc-curve_w-qcd.png?w=455" alt=""   class="size-full wp-image-1440" srcset="https://muon.files.wordpress.com/2019/02/roc-curve_w-qcd.png 277w, https://muon.files.wordpress.com/2019/02/roc-curve_w-qcd.png?w=150 150w" sizes="(max-width: 277px) 100vw, 277px" /><p id="caption-attachment-1440" class="wp-caption-text">ROC curves.  The red curve is the KNN with this metric, and the other curves close by are fancy ML algorithms.  The light blue curve is a simple cut on N-subjettiness observables, itself an important theoretical tool</p></div><br />
I imagine that some optimization could be done to close the small gap with respect to the best performing algorithms, for example in improving on the KNN.</p>
<p>The next intriguing idea presented in this paper is the fractal dimension, or <a href="https://en.wikipedia.org/wiki/Correlation_dimension" rel="noopener noreferrer" target="_blank">correlation dimension</a>, dim(Q), associated with their metric.  The interesting bit is how dim(Q) depends on the mass/energy scale Q, which can plausibly vary from a few GeV (the regime of hadronization) up to the mass of the top quark (173 GeV).  The authors compare three different sets of jets from ordinary QCD production, from W bosons decaying hadronically, and from top quarks, because one expects the detailed structure to be distinctly different, at least if viewed with the right metric.  And indeed, the variation of dim(Q) with Q is quite different:<br />
<div data-shortcode="caption" id="attachment_1442" style="width: 280px" class="wp-caption aligncenter"><img aria-describedby="caption-attachment-1442" data-attachment-id="1442" data-permalink="https://muon.wordpress.com/2019/02/24/miracles-when-you-use-the-right-metric/intrinsicdimension/" data-orig-file="https://muon.files.wordpress.com/2019/02/intrinsicdimension.png" data-orig-size="270,265" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="IntrinsicDimension" data-image-description="" data-image-caption="&lt;p&gt;dim(Q) as a function of Q for three sources of jets&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2019/02/intrinsicdimension.png?w=270" data-large-file="https://muon.files.wordpress.com/2019/02/intrinsicdimension.png?w=270" src="https://muon.files.wordpress.com/2019/02/intrinsicdimension.png?w=455" alt=""   class="size-full wp-image-1442" srcset="https://muon.files.wordpress.com/2019/02/intrinsicdimension.png 270w, https://muon.files.wordpress.com/2019/02/intrinsicdimension.png?w=150 150w" sizes="(max-width: 270px) 100vw, 270px" /><p id="caption-attachment-1442" class="wp-caption-text">dim(Q) as a function of Q for three sources of jets</p></div><br />
(Note these jets all have essentially the same energy.)   There are at least three take-away points.  First, the dim(Q) is much higher for top jets than for W and QCD jets, and W is higher than QCD. This hierarchy reflects the relative complexity of the events, and hints at new discriminating possibilities. Second, they are more similar at low scales where the structure involves hadronication, and more different at high scales which should be dominated by the decay structure.  This is born out by they decay products only curves.  Finally, there is little difference in the curves based on particles or on partons, meaning that the result is somehow fundamental and not an artifact of hadronization itself.  I find this very exciting.</p>
<p>The authors develop the correlation distance dim(Q) further.  It is a fact that a pair of jets from W decays boosted to the same degree can be described by a single variable: the ratio of their energies.  This can be mapped onto an annulus in a abstract dimensional space (see the paper for slightly more detail).  The interesting step is to look at how the complexity of individual events, reflected in dim(Q), varies around the annulus:<br />
<div data-shortcode="caption" id="attachment_1446" style="width: 465px" class="wp-caption aligncenter"><img loading="lazy" aria-describedby="caption-attachment-1446" data-attachment-id="1446" data-permalink="https://muon.wordpress.com/2019/02/24/miracles-when-you-use-the-right-metric/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang/" data-orig-file="https://muon.files.wordpress.com/2019/02/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang.png" data-orig-size="594,506" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="tSNE_W_hadrons_escheme_yphi_masked_5k_approx_perp-30_LHAang" data-image-description="" data-image-caption="&lt;p&gt;Embedding of W jets and how dim(Q) varies around the annulus and inside it&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2019/02/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang.png?w=300" data-large-file="https://muon.files.wordpress.com/2019/02/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang.png?w=455" src="https://muon.files.wordpress.com/2019/02/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang.png?w=455&#038;h=388" alt="" width="455" height="388" class="size-full wp-image-1446" srcset="https://muon.files.wordpress.com/2019/02/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang.png?w=455&amp;h=388 455w, https://muon.files.wordpress.com/2019/02/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang.png?w=150&amp;h=128 150w, https://muon.files.wordpress.com/2019/02/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang.png?w=300&amp;h=256 300w, https://muon.files.wordpress.com/2019/02/tsne_w_hadrons_escheme_yphi_masked_5k_approx_perp-30_lhaang.png 594w" sizes="(max-width: 455px) 100vw, 455px" /><p id="caption-attachment-1446" class="wp-caption-text">Embedding of W jets and how dim(Q) varies around the annulus and inside it</p></div><br />
The blue events to the lower left are simple, with just a single round dot (jet) in the center, while the red events in the upper right have two dots of nearly equal size.  The events in the center are very messy, with many dots of several sizes.   So morphology maps onto location in this kinematic plane.</p>
<p>A second illustration is provided, this time based on QCD jets of essentially the same energy.  The jet masses will span a range determined by gluon radiation and the hadronization process.  Jets at lower mass should be clean and simple while jets at high mass should show signs of structure.  This is indeed the case, as nicely illustrated in this picture:<br />
<div data-shortcode="caption" id="attachment_1447" style="width: 465px" class="wp-caption aligncenter"><img loading="lazy" aria-describedby="caption-attachment-1447" data-attachment-id="1447" data-permalink="https://muon.wordpress.com/2019/02/24/miracles-when-you-use-the-right-metric/k-medoids_qcd_jet-mass/" data-orig-file="https://muon.files.wordpress.com/2019/02/k-medoids_qcd_jet-mass.png" data-orig-size="531,552" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="K-medoids_QCD_jet-mass" data-image-description="" data-image-caption="&lt;p&gt;How complex jet substructure correlates with jet mass&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2019/02/k-medoids_qcd_jet-mass.png?w=289" data-large-file="https://muon.files.wordpress.com/2019/02/k-medoids_qcd_jet-mass.png?w=455" src="https://muon.files.wordpress.com/2019/02/k-medoids_qcd_jet-mass.png?w=455&#038;h=473" alt="" width="455" height="473" class="size-full wp-image-1447" srcset="https://muon.files.wordpress.com/2019/02/k-medoids_qcd_jet-mass.png?w=455&amp;h=473 455w, https://muon.files.wordpress.com/2019/02/k-medoids_qcd_jet-mass.png?w=144&amp;h=150 144w, https://muon.files.wordpress.com/2019/02/k-medoids_qcd_jet-mass.png?w=289&amp;h=300 289w, https://muon.files.wordpress.com/2019/02/k-medoids_qcd_jet-mass.png 531w" sizes="(max-width: 455px) 100vw, 455px" /><p id="caption-attachment-1447" class="wp-caption-text">How complex jet substructure correlates with jet mass</p></div><br />
This picture is so clear it is almost like a textbook illustration.</p>
<p>That&#8217;s it.  (There is one additional topic involving infrared divergence, but since I do not understand it I won&#8217;t try to describe it here.)  The paper is short with some startling results.  I look forward to the authors developing these studies further, and for other researchers to think about them and apply them to real examples.</p>

	<p class="info">	<em class="date"><a href="https://muon.wordpress.com/2019/02/24/miracles-when-you-use-the-right-metric/" title="11:16 am" rel="bookmark">February 24, 2019 at 11:16 am</a></em>				<em class="comments-popup">
		<a href="https://muon.wordpress.com/2019/02/24/miracles-when-you-use-the-right-metric/#respond" class="commentlink" >Leave a comment</a>		</em>
			</p>

</div>

	
<div id="post-1420" class="entry post-1420 post type-post status-publish format-standard hentry category-particle-physics">

	<h2><a href="https://muon.wordpress.com/2014/11/16/quark-contact-interactions-at-the-lhc/">Quark contact interactions at the&nbsp;LHC</a></h2>

	<p>So far, no convincing sign of new physics has been uncovered by the CMS and ATLAS collaborations.  Nonetheless, the scientists continue to look using a wide variety of approaches.  For example, a monumental work on the coupling of the Higgs boson to vector particles has been posted by the CMS Collaboration (<a href="http://arxiv.org/abs/1411.3441">arXiv:1411.3441</a>).   The authors conducted a thorough and very sophisticated statistical analysis of the kinematic distributions of all relevant decay modes, with the conclusion that the data for the Higgs boson are fully consistent with the standard model expectation.  The analysis and article are too long for a blog post, however, so please see the paper if you want to learn the details.</p>
<p>The ATLAS Collaboration posted a paper on generic searches for new physics signals based on events with three leptons (e, &mu; and &tau;). This paper (<a href="http://arxiv.org/abs/1411.2921">arXiv:1411.2921</a>) is longish one describing a broad-based search with several categories of events defined by lepton flavor and charge and other event properties.  In all categories the observation confirms the predictions based on standard model processes: the smallest p-value is 0.05.</p>
<p>A completely different search for new physics based on a decades-old concept was posted by CMS (<a href="http://arxiv.org/abs/1411.2646">arXiv:1411.2646</a>).  We all know that the Fermi theory of weak interactions starts with a so-called <i>contact interaction</i> characterized by an interaction vertex with four legs.  The Fermi constant serves to parametrize the interaction, and the participation of a vector boson is immaterial when the energy of the interaction is low compared to the boson mass. This framework is the starting point for other effective theories, and has been employed at hadron colliders when searching for deviations in quark-quark interactions, as might be observable if quarks were composite.</p>
<p>The experimental difficulty in studying high-energy quark-quark scattering is that the energies of the outgoing quarks are not so well measured as one might like. (First, the hadronic jets that materialize in the detector do not precisely reflect the quark energies, and second, jet energies cannot be measured better than a few percent.) It pays, therefore, to avoid using energy as an observable and to get the most out of angular variables, which are well measured.  Following analyses done at the Tevatron, the authors use a variable &chi; = exp(|y<sub>1</sub>-y<sub>2</sub>|), which is a simple function of the quark scattering angle in the center-of-mass frame.   The distribution of events in &chi; can be unambiguously predicted in the standard model and in any other hypothetical model, and confronted with the data.  So we have a nice case for a goodness-of-fit test and pairwise hypothesis testing.</p>
<p>The traditional parametrization of the interaction Lagrangian is:<br />
<a href="https://muon.files.wordpress.com/2014/11/contact_lagrangian.png"><img data-attachment-id="1422" data-permalink="https://muon.wordpress.com/2014/11/16/quark-contact-interactions-at-the-lhc/contact_lagrangian/" data-orig-file="https://muon.files.wordpress.com/2014/11/contact_lagrangian.png" data-orig-size="758,65" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="contact_lagrangian" data-image-description="" data-image-caption="" data-medium-file="https://muon.files.wordpress.com/2014/11/contact_lagrangian.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/11/contact_lagrangian.png?w=455" src="https://muon.files.wordpress.com/2014/11/contact_lagrangian.png?w=455&#038;h=39" alt="contact_lagrangian"   class="alignnone size-large wp-image-1422" srcset="https://muon.files.wordpress.com/2014/11/contact_lagrangian.png?w=455&amp;h=39 455w, https://muon.files.wordpress.com/2014/11/contact_lagrangian.png?w=150&amp;h=13 150w, https://muon.files.wordpress.com/2014/11/contact_lagrangian.png?w=300&amp;h=26 300w, https://muon.files.wordpress.com/2014/11/contact_lagrangian.png 758w" sizes="(max-width: 455px) 100vw, 455px" /></a><br />
where the &eta; parameters have values -1, 0, +1 and specify the chirality of the interaction; the key parameter is the mass scale &Lambda;.  An important detail is that this interaction Lagrangian can interfere with the standard model piece, and the interference can be either destructive or constructive, depending on the values of the &eta; parameters.</p>
<p>The analysis proceeds exactly as one would expect: events must have at least two jets, and when there are more than two, the two highest-pT jets are used and the others ignored.  Distributions of &chi; are formed for several ranges of di-jet invariant mass, M<sub>JJ</sub>, which extends as high as 5.2 TeV.  The measured &chi; distributions are unfolded, i.e., the effects of detector resolution are removed from the distribution on a statistical basis.  The main sources of systematic uncertainty come from the jet energy scale and resolution and are based on an extensive parametrization of jet uncertainties.</p>
<p>Since one is looking for deviations with respect to the standard model prediction, it is very important to have an accurate prediction.  Higher-order terms must be taken into account; these are available at next-to-leading order (NLO). In fact, even electroweak corrections are important and amount to several percent as a strong function of &chi; &#8212; see the plot on the right. <a href="https://muon.files.wordpress.com/2014/11/ewk_allmassbins_r05_authors.png"><img data-attachment-id="1423" data-permalink="https://muon.wordpress.com/2014/11/16/quark-contact-interactions-at-the-lhc/ewk_allmassbins_r05_authors/" data-orig-file="https://muon.files.wordpress.com/2014/11/ewk_allmassbins_r05_authors.png" data-orig-size="255,255" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="EWK_AllMassBins_R05_authors" data-image-description="" data-image-caption="" data-medium-file="https://muon.files.wordpress.com/2014/11/ewk_allmassbins_r05_authors.png?w=255" data-large-file="https://muon.files.wordpress.com/2014/11/ewk_allmassbins_r05_authors.png?w=255" src="https://muon.files.wordpress.com/2014/11/ewk_allmassbins_r05_authors.png?w=455" alt="EWK_AllMassBins_R05_authors"   class="alignright size-full wp-image-1423" srcset="https://muon.files.wordpress.com/2014/11/ewk_allmassbins_r05_authors.png 255w, https://muon.files.wordpress.com/2014/11/ewk_allmassbins_r05_authors.png?w=150 150w" sizes="(max-width: 255px) 100vw, 255px" /></a> The scale uncertainties are a few percent (again showing the a very precise SM prediction is non-trivial event for pp&rarr;2J) and fortunately the PDF uncertainties are small, at the percent level.  Theoretical uncertainties dominate for M<sub>JJ</sub> near 2 TeV, while statistical uncertainties dominate for M<sub>JJ</sub> above 4 TeV.</p>
<p>The money plot is this one:<br />
<a href="https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png"><img data-attachment-id="1424" data-permalink="https://muon.wordpress.com/2014/11/16/quark-contact-interactions-at-the-lhc/datacard_shapelimit_combined/" data-orig-file="https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png" data-orig-size="842,595" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="datacard_shapelimit_combined" data-image-description="" data-image-caption="&lt;p&gt;Measured and predicted distributions in &amp;chi;&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png?w=455" src="https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png?w=455" alt="Measured and predicted distributions in &chi;" class="size-large wp-image-1424" srcset="https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png?w=455 455w, https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png?w=150 150w, https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png?w=300 300w, https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png?w=768 768w, https://muon.files.wordpress.com/2014/11/datacard_shapelimit_combined.png 842w" sizes="(max-width: 455px) 100vw, 455px" /></a><br />
Optically speaking, the plot is not exciting: the &chi; distributions are basically flat and deviations due to a mass scale &Lambda; = 10 TeV would be mild.   Such deviations are not observed.   Notice, though, that the electroweak corrections do improve the agreement with the data in the lowest &chi; bins.  Loosely speaking, this improvement corresponds to about one standard deviation and therefore would be significant if CMS actually had evidence for new physics in these distributions.  As far as limits are concerned, the electroweak corrections are &#8220;worth&#8221; 0.5 TeV.</p>
<p>The statistical (in)significance of any deviation is quantified by a ratio of log-likelihoods: q = -2ln(L<sub>SM+NP</sub>/L<sub>SM</sub>) where SM stands for standard model and NP for new physics (i.e., one of distinct possibilities given in the interaction Lagrangian above).   Limits are derived on the mass scale &Lambda; depending on assumed values for the &eta; parameters; they are very nicely summarized in this graph:<a href="https://muon.files.wordpress.com/2014/11/ci_limits_summary.png"><img data-attachment-id="1425" data-permalink="https://muon.wordpress.com/2014/11/16/quark-contact-interactions-at-the-lhc/ci_limits_summary/" data-orig-file="https://muon.files.wordpress.com/2014/11/ci_limits_summary.png" data-orig-size="842,595" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="CI_limits_summary" data-image-description="" data-image-caption="&lt;p&gt;Summary of limits placed on mass scales.&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/11/ci_limits_summary.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/11/ci_limits_summary.png?w=455" src="https://muon.files.wordpress.com/2014/11/ci_limits_summary.png?w=455" alt="Summary of limits placed on mass scales." class="size-large wp-image-1425" srcset="https://muon.files.wordpress.com/2014/11/ci_limits_summary.png?w=455 455w, https://muon.files.wordpress.com/2014/11/ci_limits_summary.png?w=150 150w, https://muon.files.wordpress.com/2014/11/ci_limits_summary.png?w=300 300w, https://muon.files.wordpress.com/2014/11/ci_limits_summary.png?w=768 768w, https://muon.files.wordpress.com/2014/11/ci_limits_summary.png 842w" sizes="(max-width: 455px) 100vw, 455px" /></a><br />
The limits for contact interactions are roughly at the 10 TeV scale &#8212; well beyond the center-of-mass energy of 8 TeV.  I like this way of presenting the limits: you see the expected value (black dashed line) and an envelope of expected statistical fluctuations from this expectation, with the observed value clearly marked as a red line.   All limits are slightly more stringent than the expected ones (these are not independent of course).  </p>
<p>The authors also considered models of extra spatial dimensions and place limits on the scale of the extra dimensions at the 7 TeV level.</p>
<p>So, absolutely no sign of new physics here.  The LHC will turn on in 2015 at a significantly higher center-of-mass energy (13 TeV), and given the ability of this analysis to probe mass scales well above the proton-proton collision energy, a study of the &chi; distribution will be interesting.</p>

	<p class="info">	<em class="date"><a href="https://muon.wordpress.com/2014/11/16/quark-contact-interactions-at-the-lhc/" title="10:45 am" rel="bookmark">November 16, 2014 at 10:45 am</a></em>				<em class="comments-popup">
		<a href="https://muon.wordpress.com/2014/11/16/quark-contact-interactions-at-the-lhc/#comments" class="commentlink" >1 comment</a>		</em>
			</p>

</div>

	
<div id="post-1410" class="entry post-1410 post type-post status-publish format-standard hentry category-particle-physics">

	<h2><a href="https://muon.wordpress.com/2014/11/09/looking-for-milli-charged-particles-at-the-lhc/">Looking for milli-charged particles at the&nbsp;LHC</a></h2>

	<p>Andrew Haas, Chris Hill, Eder Izaguirre and Itay Yavin posted an interesting and imaginative proposal last week to search for milli-charged particles at ATLAS and CMS (<a href="http://arxiv.org/abs/1410.6816">arXiv:1410.6816</a>) and I think it is worth taking a look.</p>
<p>Milli-charged particles can arise in some models with extra gauge bosons.  The word &#8220;milli-charged&#8221; refers to the fact that the electric charge is much less than the charge of the electron.  Such small charges do not arise due to some fundamental representation in the gauge theory.  Rather, they arise through a (kinetic) mixing of the new gauge boson with the hyper charge field B<sub>&mu;</sub>.  If e&#8217; is the charge associated with the new gauge boson and &kappa; controls the degree of mixing, then the electric charge of the new particle &psi; is &epsilon; = &kappa;e&#8217; cos&theta;<sub>W</sub>/e.    The weak charge is smaller by a factor of tan&theta;<sub>W</sub>.   So the motivation for the search is good and the phenomenology is clear enough, and general.</p>
<p>A pair of hypothetical milli-charged particles would be produced through the Drell-Yan process.  There are contributions from both virtual photon and Z exchange; nonetheless, the cross section is small because the charge is small.   If the milli-charged particles are light enough, they can also be produced in decays of J/&psi; and &Upsilon; mesons.  The authors provide a plot:</p>
<div data-shortcode="caption" id="attachment_1412" style="width: 610px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png"><img aria-describedby="caption-attachment-1412" data-attachment-id="1412" data-permalink="https://muon.wordpress.com/2014/11/09/looking-for-milli-charged-particles-at-the-lhc/dy_prodxs_lhc/" data-orig-file="https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png" data-orig-size="600,394" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="DY_prodXS_LHC" data-image-description="" data-image-caption="&lt;p&gt;Cross section for the production of a pair of milli-charged particles&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png?w=455" src="https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png?w=455" alt="Cross section for the production of a pair of milli-charged particles"   class="size-full wp-image-1412" srcset="https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png?w=455 455w, https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png?w=150 150w, https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png?w=300 300w, https://muon.files.wordpress.com/2014/11/dy_prodxs_lhc.png 600w" sizes="(max-width: 455px) 100vw, 455px" /></a><p id="caption-attachment-1412" class="wp-caption-text">Cross section for the production of a pair of milli-charged particles</p></div>
<p>Detecting a milli-charged particle is not easy because the ionization they produce as they pass through matter is much smaller than that of an electron, muon or other standard charged particle.  (Recall that the ionization rate is proportional to the square of the charge of the particle.) Consequently, the trail of ions is much sparser and the amount of charge in a ionization cluster is smaller, resulting in a substantially or even dramatically reduced signal from a detector element (such as a silicon strip, proportional wire chamber or scintillator).  So they cannot be reliably reconstructed as tracks in an LHC or other general-purpose detector.  In fact, some searches have been done treating milli-charged particles as effectively invisible &#8211; i.e., as producing a missing energy signature.   Such approaches are not effective, however, due to the large background from Z&rarr;&nu;&nu;.</p>
<p>A special detector is required and this is the crux of the Haas, Hill, Izaguirre and Yavin proposal.</p>
<p>This special detector must have an unusually low threshold for ionization signals.  In fact, normal particles will produce relatively large signals that help reject them.  Clearly, the sensitivity to very small milli-charges, &epsilon;, is determined by how low the noise level in the detector is.  The main problem is that normal particles will swamp and bury any signal from milli-charged particles that may be present.  One needs to somehow shield the detector from normal particles so that one can look for small-amplitude signals from milli-charged particles.</p>
<p>Fortunately, the main challenge of detecting milli-charged particles turns out to be a virtue: normal particles will eventually be absorbed by bulk matter &#8211; this is the principle behind the calorimeter, after all.  Milli-charged particles, however, lose their energy through ionization at a much slower rate and will pass through the calorimeters with little attenuation.   This is the principle of the beam-dump experiment: look for particle that are <i>not</i> absorbed the way the known particles are.   (Implicitly we assume that the milli-charged particles have no strong interactions.)  </p>
<p>The authors propose to install a carefully-crafted scintillator detector behind a thick wall in the CMS and/or ATLAS caverns.  Typically, electronic readout devices for the normal detector are housed in a shielded room not far from the detector.  This new scintillator detector would be installed inside this so-called counting room.</p>
<div data-shortcode="caption" id="attachment_1414" style="width: 465px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png"><img aria-describedby="caption-attachment-1414" data-attachment-id="1414" data-permalink="https://muon.wordpress.com/2014/11/09/looking-for-milli-charged-particles-at-the-lhc/experimentschematicmillicharged/" data-orig-file="https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png" data-orig-size="1024,768" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="ExperimentSchematicMillicharged" data-image-description="" data-image-caption="&lt;p&gt;Schematics drawing showing how the scintillator detector would be placed in a counting room, away from the interaction point (IP)&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png?w=455" src="https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png?w=455&#038;h=341" alt="Schematics drawing showing how the scintillator detector would be placed in a counting room, away from the interaction point (IP)"   class="size-large wp-image-1414" srcset="https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png?w=455&amp;h=341 455w, https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png?w=910&amp;h=682 910w, https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png?w=150&amp;h=113 150w, https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png?w=300&amp;h=225 300w, https://muon.files.wordpress.com/2014/11/experimentschematicmillicharged.png?w=768&amp;h=576 768w" sizes="(max-width: 455px) 100vw, 455px" /></a><p id="caption-attachment-1414" class="wp-caption-text">Schematics drawing showing how the scintillator detector would be placed in a counting room, away from the interaction point (IP)</p></div>
<p>The scintillator detector is not ordinary.  It must be sensitive to rather small ionization signals which means the amplification must be large and the noise rate low.  In order to fight spurious signals, the detector is divided into three parts along the flight path of the milli-charged particle and a coincidence of the three is required.  In order to fight backgrounds from ordinary particles produced in the pp collisions, the detector is segmented, with each segment subtending only a very small solid angle: essentially each segment (which consists of three longitudinal pieces) forms a telescope that points narrowly at the interaction point, i.e., the origin of the milli-charged particles.   Even with many such segments (&#8220;bars&#8221;), the total solid angle is miniscule so only a very small fraction of the signal would be detected &#8211; we say that the acceptance is very small.   Sensitivity to the production of milli-charged particles is possible because the luminosity of the LHC will be high.   Basically, the product of the cross section, the acceptance and the luminosity is a few even though the acceptance is so small.  The authors estimated the reach of their experiment and produced this figure:</p>
<p><a href="https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png"><img data-attachment-id="1417" data-permalink="https://muon.wordpress.com/2014/11/09/looking-for-milli-charged-particles-at-the-lhc/sensitivitythreelayersfigmillicharged/" data-orig-file="https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png" data-orig-size="600,393" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="SensitivityThreeLayersFigMillicharged" data-image-description="" data-image-caption="" data-medium-file="https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png?w=455" src="https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png?w=455" alt="SensitivityThreeLayersFigMillicharged"   class="alignnone size-full wp-image-1417" srcset="https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png?w=455 455w, https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png?w=150 150w, https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png?w=300 300w, https://muon.files.wordpress.com/2014/11/sensitivitythreelayersfigmillicharged.png 600w" sizes="(max-width: 455px) 100vw, 455px" /></a></p>
<p>It is worth pointing out that this detector runs parasitically &#8211; it will not be providing triggers to the ATLAS or CMS detectors.   Its time resolution should be good, about 10 ns, so it might be possible to correlate a signal from a milli-charged particle with a particular bunch crossing, but this is not really needed.</p>
<p>The upcoming run will be an exciting time to try this search.   Evidence for milli-charged particles would be a huge discovery, of course.   I do not know the status of this proposal vis-a-vis CERN and the LHC experiments.  But if a signal were observed, it would clearly be easy to enhance it by building more detector.  My opinion is that this is a good idea, and I hope others will agree.</p>

	<p class="info">	<em class="date"><a href="https://muon.wordpress.com/2014/11/09/looking-for-milli-charged-particles-at-the-lhc/" title="10:21 am" rel="bookmark">November 9, 2014 at 10:21 am</a></em>				<em class="comments-popup">
		<a href="https://muon.wordpress.com/2014/11/09/looking-for-milli-charged-particles-at-the-lhc/#comments" class="commentlink" >1 comment</a>		</em>
			</p>

</div>

	
<div id="post-1397" class="entry post-1397 post type-post status-publish format-standard hentry category-particle-physics">

	<h2><a href="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/">The CMS kinematic&nbsp;edge</a></h2>

	<p>Does CMS observe an excess that corresponds to a signal for Supersymmetry?   Opinions differ.</p>
<p>This week a paper appeared with the statement &#8220;&#8230;CMS has reported an intriguing excess of events with respect to the ones expected in the SM&#8221; (Huang &amp; Wagner, <a href="http://arxiv.org/abs/1410.4998">arXiv:1410.4998</a>).  And last month another phenomenology paper   appeared with the title &#8220;Interpreting a CMS lljjpTmiss Excess With the Golden Cascade of the MSSM&#8221; (Allanach, Raklev and Kvellestad <a href="http://arxiv.org/abs/1409.3532">arXiv:1409.3532</a>).  Both studies are based on a preliminary CMS report (<a href="http://cds.cern.ch/record/1751493/files/SUS-12-019-pas.pdf">CMS PAS SUS-12-019</a>, Aug. 24 2014), which ends with the statement <i>&#8220;We do not observe evidence for a statistically significant signal.&#8221;</i>  </p>
<p>What is going on here?</p>
<p>The CMS search examines the di-lepton invariant mass distribution for a set of events which have, in addition to two energetic and isolated leptons, missing transverse momentum (pTmiss) and two jets.  In cascade decays of SUSY particles, &chi;02 &rarr; &chi;01 l+l-, a kind of hard edge appears at the phase space limit for the two leptons l+l-, as pointed out many years ago (PRD 55 (1997) 5520).   When distinguishing a signal from background, a sharp edge is almost as good as a peak, so this is a nice way to isolate a signal if one exists.   An edge can also be observed in decays of sleptons.  The CMS search is meant to be as general as possible.</p>
<p>In order to remove the bulk of SM events producing a pair of leptons, a significant missing energy is required, as expected from a pair of neutralinos &chi;01.  Furthermore, other activity in the event is expected (recall that there will be <i>two</i> supersymmetric particles in the event) so the search demands at least two jets.  Hence:  ll+jj+pTmiss.</p>
<p>A crucial feature of the analysis is motivated by the phenomenology of SUSY cascade decays: for the signal, the two leptons will have the same flavor (ee or &mu;&mu;), while most of the SM backgrounds will be flavor blind (so e&mu; also is expected).  By comparing the Mll spectrum for same-flavor and for opposite-flavor leptons, an excess might be observed with little reliance on simulations.  Only the Drell-Yan background does not appear in the opposite-flavor sample at the same level as in the same-flavor sample, but a hard cut on pTmiss (also called ETmiss) removes most of the DY background.  (I am glossing over careful and robust measurements of the relative e and &mu; reconstruction and trigger efficiencies &#8211; see the note for those details, especially Section 4.)</p>
<p>The CMS analyzers make an important distinction between &#8220;central&#8221; leptons with |&eta;|&lt;1.4 and &quot;forward&quot; leptons 1.6&lt;|&eta;|&lt;2.4 motivated by the idea that supersymmetric particles will be centrally produced due to their high mass, and an excess may be more pronounced when both leptons are central.</p>
<p>A search for a kinematic edge proceed just as you would expect &#8211; a series of fits is performed with the edge placed at different points across a wide range of invariant mass Mll.  The model for the Mll spectrum has three components: the flavor-symmetric backgrounds, dominated by tt, the DY background and a hypothetical signal.  Both the flavor-symmetric and the DY components are described by heuristic analytical functions with several free parameters.  The signal is a triangle convolved with a Gaussian to represent the resolution on Mll.  Most of the model parameters are determined in fits with enhanced DY contributions, and through the simultaneous fit to the opposite-flavor sample.  For the search, only three parameters are free: the signal yield in the central and forward regions and the position of the kinematic edge.</p>
<p>The best fitted value for the edge is y = 78.7&plusmn;1.4 GeV.  At that point, an excess is observed with a local statistical significance of 2.4&sigma;, in the central region.  There is no excess in the forward region. Here is the plot:</p>
<a href="https://muon.files.wordpress.com/2014/10/cms-edge.png"><img data-attachment-id="1400" data-permalink="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/cms-edge/" data-orig-file="https://muon.files.wordpress.com/2014/10/cms-edge.png" data-orig-size="1181,1383" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="CMS edge" data-image-description="" data-image-caption="&lt;p&gt;Fit to the same-flavor dilepton mass distribution&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/cms-edge.png?w=256" data-large-file="https://muon.files.wordpress.com/2014/10/cms-edge.png?w=455" src="https://muon.files.wordpress.com/2014/10/cms-edge.png?w=455&#038;h=532" alt="Fit to the same-flavor dilepton mass distribution"   class="size-large wp-image-1400" srcset="https://muon.files.wordpress.com/2014/10/cms-edge.png?w=455&amp;h=532 455w, https://muon.files.wordpress.com/2014/10/cms-edge.png?w=910&amp;h=1064 910w, https://muon.files.wordpress.com/2014/10/cms-edge.png?w=128&amp;h=150 128w, https://muon.files.wordpress.com/2014/10/cms-edge.png?w=256&amp;h=300 256w, https://muon.files.wordpress.com/2014/10/cms-edge.png?w=768&amp;h=899 768w, https://muon.files.wordpress.com/2014/10/cms-edge.png?w=874&amp;h=1024 874w" sizes="(max-width: 455px) 100vw, 455px" /></a>
<p>The green triangle represents the fitted signal.  The red peak is, of course, the Z resonance.  Here is the distribution for the forward region:</p>
<div data-shortcode="caption" id="attachment_1401" style="width: 465px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/10/cms-edge-of.png"><img aria-describedby="caption-attachment-1401" data-attachment-id="1401" data-permalink="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/cms-edge-of/" data-orig-file="https://muon.files.wordpress.com/2014/10/cms-edge-of.png" data-orig-size="1181,1383" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="CMS edge OF" data-image-description="" data-image-caption="&lt;p&gt;Fit to the opposite (electron-muon) invariant mass distribution&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=256" data-large-file="https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=455" src="https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=455&#038;h=532" alt="Fit to the opposite invariant mass distribution for the forward sample"   class="size-large wp-image-1401" srcset="https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=455&amp;h=532 455w, https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=910&amp;h=1064 910w, https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=128&amp;h=150 128w, https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=256&amp;h=300 256w, https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=768&amp;h=899 768w, https://muon.files.wordpress.com/2014/10/cms-edge-of.png?w=874&amp;h=1024 874w" sizes="(max-width: 455px) 100vw, 455px" /></a><p id="caption-attachment-1401" class="wp-caption-text">Fit to the opposite (electron-muon) invariant mass distribution</p></div>
<p>Comparing the two distributions and ignoring the Z peak, there does indeed seem to be an excess of ee and &mu;&mu; pairs for Mll &lt; 80 GeV or so.   One can understand why the theorists would find this intriguing&#8230;</p>
<p>CMS made a second treatment of their data by defining a mass region 20 &lt; Mll &lt; 70 GeV and simply counting the number of events, thereby avoiding any assumptions about the shape of a signal.  For this treatment, one wants to compare the data to the prediction, with suitable corrections for efficiencies, etc.  Here are the plots:</p>
<a href="https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png"><img data-attachment-id="1402" data-permalink="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/cms-mll-comparison/" data-orig-file="https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png" data-orig-size="817,495" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="CMS Mll comparison" data-image-description="" data-image-caption="&lt;p&gt;Comparison of Mll distributions for data (dots) and the prediction (solid lines).  Left: central.  Right: forward.&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png?w=455" src="https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png?w=455&#038;h=275" alt="Comparison of Mll distributions for data (dots) and the prediction (solid lines).  Left: central.  Right: forward."   class="size-large wp-image-1402" srcset="https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png?w=455&amp;h=275 455w, https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png?w=150&amp;h=91 150w, https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png?w=300&amp;h=182 300w, https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png?w=768&amp;h=465 768w, https://muon.files.wordpress.com/2014/10/cms-mll-comparison.png 817w" sizes="(max-width: 455px) 100vw, 455px" /></a>
<p>By eye one can notice a tendency of the real data (dots) to fall above the prediction (solid line histogram).  This tendency is much stronger for the events with two central leptons compared to the events with at least one forward lepton.  Counting, CMS reports 860 observed compared to 730&plusmn;40 predicted (central) and 163 observed for 157&plusmn;16 forward.  The significance is 2.6&sigma; for the central di-leptons.</p>
<p>CMS provides a kind of teaser plot, in which they simulate three signals from the production of sbottom squarks.  As you can see here, two of the models describe the apparent excess well:</p>
<div data-shortcode="caption" id="attachment_1404" style="width: 608px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png"><img aria-describedby="caption-attachment-1404" data-attachment-id="1404" data-permalink="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/cms-edge-sbottoms/" data-orig-file="https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png" data-orig-size="598,549" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="CMS edge sbottoms" data-image-description="" data-image-caption="&lt;p&gt;Comparison to sbottom signals&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png?w=455" src="https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png?w=455" alt="Comparison to sbottom signals"   class="size-full wp-image-1404" srcset="https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png?w=455 455w, https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png?w=150 150w, https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png?w=300 300w, https://muon.files.wordpress.com/2014/10/cms-edge-sbottoms.png 598w" sizes="(max-width: 455px) 100vw, 455px" /></a><p id="caption-attachment-1404" class="wp-caption-text">Comparison to sbottom signals</p></div>
<p>So why is this not a discovery?</p>
<p>First of all, the statistical significance is under 3&sigma; so formally speaking, this not even &#8220;evidence.&#8221;  More importantly, the &#8220;look-elsewhere effect&#8221; has not been taken into account, as stated clearly in the CMS note.  In other words, the significance for the fit is 2.4&sigma; <i>when you choose 78.7 GeV for the position of the edge.</i>   If you allow for any position of the edge within some wide range of Mll, then the chance that you observe an excess <i>somewhere in that range</i> is much greater than 1%.  Similarly, the counting excess is 2.6&sigma; for the specific box 20 &lt; Mll &lt; 70 GeV, but if you consider many different boxes, the chance to observe such a single excess <i>somewhere</i> is not so small.   For this reason, the CMS Collaboration states that there is no statistically significant excess.</p>
<p>That said, the agreement of the simulated sbottom signals with the data is striking, even granted that there are many free parameters here that one can tune to get a good description.  The Allanach et al. paper reports a scan in MSSM parameter space to find which physical SUSY parameters are consistent with the CMS data.  They impose a few theoretical constraints that are not crucial at this stage, and perform a scan with simulated signals to see which ranges of parameters reproduce the CMS data and also respect constraints from other ATLAS and CMS searches.  An example model is shown here: </p>
<div data-shortcode="caption" id="attachment_1406" style="width: 465px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png"><img aria-describedby="caption-attachment-1406" data-attachment-id="1406" data-permalink="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/200_300-eps-converted-to/" data-orig-file="https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png" data-orig-size="866,558" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="200_300-eps-converted-to" data-image-description="" data-image-caption="&lt;p&gt;Example spectrum from Allanach et al.&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png?w=455" src="https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png?w=455&#038;h=293" alt="Example spectrum from Allanach et al."   class="size-large wp-image-1406" srcset="https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png?w=455&amp;h=293 455w, https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png?w=150&amp;h=97 150w, https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png?w=300&amp;h=193 300w, https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png?w=768&amp;h=495 768w, https://muon.files.wordpress.com/2014/10/200_300-eps-converted-to.png 866w" sizes="(max-width: 455px) 100vw, 455px" /></a><p id="caption-attachment-1406" class="wp-caption-text">Example spectrum from Allanach et al.</p></div>
<p>Wide ranges of sparticle masses are allowed, but there are strong constraints among them coming from the well-measured position of the edge.  Constraints from (g-1)&mu; are respected and the relic density is good.  Best of all, prospects for discovering one of these models at Run 2 are good &#8212; if such a signal really is present of course.</p>
<p>The Huang &amp; Wagner paper focuses on the sbottom scenario mentioned in the CMS paper, and does a more detailed and refined analysis.  They define two similar scenarios, here is the scheme for the first one:</p>
<div data-shortcode="caption" id="attachment_1407" style="width: 633px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/10/sbottom-scenario.png"><img aria-describedby="caption-attachment-1407" data-attachment-id="1407" data-permalink="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/sbottom-scenario/" data-orig-file="https://muon.files.wordpress.com/2014/10/sbottom-scenario.png" data-orig-size="623,454" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="sbottom scenario" data-image-description="" data-image-caption="&lt;p&gt;Huang &amp;amp; Wagner sbottom scenario&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/sbottom-scenario.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/10/sbottom-scenario.png?w=455" src="https://muon.files.wordpress.com/2014/10/sbottom-scenario.png?w=455" alt="Huang &amp; Wagner sbottom scenario"   class="size-full wp-image-1407" srcset="https://muon.files.wordpress.com/2014/10/sbottom-scenario.png?w=455 455w, https://muon.files.wordpress.com/2014/10/sbottom-scenario.png?w=150 150w, https://muon.files.wordpress.com/2014/10/sbottom-scenario.png?w=300 300w, https://muon.files.wordpress.com/2014/10/sbottom-scenario.png 623w" sizes="(max-width: 455px) 100vw, 455px" /></a><p id="caption-attachment-1407" class="wp-caption-text">Huang &amp; Wagner sbottom scenario</p></div>
<p>They do not perform a scan of parameter space; rather, they select model parameters by hand to provide pertinent examples.  They specifically focus on the relic density and (g-2)&mu; to make sure they their model can explain these facts.  They explain their reasoning clearly in their paper.  Their hand-tuned model does a nice job matching the CMS data.  Of course, it also evades direct searches for sbottoms by both ATLAS and CMS.  </p>
<p>What about the ATLAS 8 TeV data?  For now, we must wait.</p>

	<p class="info">	<em class="date"><a href="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/" title="5:29 pm" rel="bookmark">October 26, 2014 at 5:29 pm</a></em>				<em class="comments-popup">
		<a href="https://muon.wordpress.com/2014/10/26/the-cms-kinematic-edge/#comments" class="commentlink" >2 comments</a>		</em>
			</p>

</div>

	
<div id="post-1393" class="entry post-1393 post type-post status-publish format-standard hentry category-particle-physics">

	<h2><a href="https://muon.wordpress.com/2014/10/19/enhanced-higgs-to-tautau-search-with-deep-learning/">Enhanced Higgs to tau+tau- Search with Deep&nbsp;Learning</a></h2>

	<p>&#8220;Enhanced Higgs to tau+tau- Search with Deep Learning&#8221; &#8211; that is the title of a new article posted to the archive this week by Daniel Whiteson and two collaborators from the Computer Science Department at UC Irvine (<a href="http://arxiv.org/abs/1410.3469">1410.3469</a>).   While the title may be totally obscure to someone outside of collider physics, it caught my immediate attention because I am working on a similar project (to be released soon).</p>
<p>Briefly: the physics motivation comes from the need for a stronger signal for Higgs decays to &tau;<sup>+</sup>&tau;<sup>&#8211;</sup>, which are important for testing the Higgs couplings to fermions (specifically, leptons).   The scalar particle with a mass of 125 GeV looks very much like the standard model Higgs boson, but tests of couplings, which are absolutely crucial, are not very precise yet.  In fact, indirect constraints are stronger than direct ones at the present time.  So boosting the sensitivity of the LHC data to Higgs decays to fermions is an important task.</p>
<p>The meat of the article concerns the comparisons of <i>shallow</i> artificial neural networks, which contain only one or two hidden layers, and <i>deep</i> artificial neural networks, which have many.  Deep networks are harder to work with than shallow ones, so the question is: does one really gain anything?   The answer is: yes, its like increasing your luminosity by 25%.</p>
<p>This case study considers final states with two oppositely-charged leptons (e or &mu;) and missing transverse energy.  The Higgs signal must be separated from the Drell-Yan production of &tau; pairs, especially Z&rarr;&tau;<sup>+</sup>&tau;<sup>&#8211;</sup>, on a statistical basis.  It appears that no other backgrounds (such as W pair or top pair production) were considered, so this study is a purely technical one.  Nonetheless, there is plenty to be learned from it.</p>
<p>Whiteson, Baldi and Sadowski make a distinction between <i>low-level variables</i>, which include the basic kinematic observables for the leptons and jets, and the <i>high-level variables</i>, which include derived kinematic quantities such as invariant masses, differences in angles and pseudorapidity, sphericity, etc.  I think this distinction and the way they compare the impact of the two sets is interesting.  </p>
<p>The question is: if a sophisticated artificial neural network is able to develop complex functions of the low-level variables through training and optimization, isn&#8217;t it redundant to provide derived kinematic quantities as additional inputs?   More sharply: does the neural network need &#8220;human assistance&#8221; to do its job?</p>
<p>The answer is clear: human assistance does help the performance of even a deep neural network with thousands of neurons and millions of events for training.  Personally I am not surprised by this, because there is physics insight behind most if not all of the high-level variables &#8212; they are not just arbitrary functions of the low-level variables.  So these specific functions carry physics meaning and fall somewhere between arbitrary functions of the input variables and brand new information (or features).   I admit, though, that &#8220;physics meaning&#8221; is a nebulous concept and my statement is vague&#8230;</p>
<div data-shortcode="caption" id="attachment_1394" style="width: 442px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/10/dnn_bargraph.png"><img aria-describedby="caption-attachment-1394" data-attachment-id="1394" data-permalink="https://muon.wordpress.com/2014/10/19/enhanced-higgs-to-tautau-search-with-deep-learning/dnn_bargraph/" data-orig-file="https://muon.files.wordpress.com/2014/10/dnn_bargraph.png" data-orig-size="432,288" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="DNN_bargraph" data-image-description="" data-image-caption="&lt;p&gt;Comparison of the performance of shallow networks and deep networks, and also of low-level and high-level variables&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/dnn_bargraph.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/10/dnn_bargraph.png?w=432" src="https://muon.files.wordpress.com/2014/10/dnn_bargraph.png?w=455" alt="Comparison of the performance of shallow networks and deep networks, and also of low-level and high-level variables"   class="size-full wp-image-1394" srcset="https://muon.files.wordpress.com/2014/10/dnn_bargraph.png 432w, https://muon.files.wordpress.com/2014/10/dnn_bargraph.png?w=150 150w, https://muon.files.wordpress.com/2014/10/dnn_bargraph.png?w=300 300w" sizes="(max-width: 432px) 100vw, 432px" /></a><p id="caption-attachment-1394" class="wp-caption-text">Comparison of the performance of shallow networks and deep networks, and also of low-level and high-level variables</p></div>
<p>The authors applied state of the art techniques for this study, including optimization with respect to <i>hyperparameters</i>, i.e., the parameters that concern the details of the training of the neural network (learning speed, `velocity&#8217; and network architecture).  A lot of computer cycles were burnt to carry out these comparisons!</p>
<p>Deep neural networks might seem like an obvious way to go when trying to isolate rare signals.  There are real, non-trivial stumbling blocks, however.  An important one is the <i>vanishing gradient</i> problem.   If the number of hidden nodes is large (imagine eight layers with 500 neurons each) then training by back-propagation fails because it cannot find a significantly non-zero gradient with respect to the weights and offsets of the all the neurons.  If the gradient vanishes, then the neural network cannot figure out which way to evolve so that it performs well.   Imagine a vast flat space with a minimum that is localized and far away.   How can you figure out which way to go to get there if the region where you are is nearly perfectly flat?</p>
<p>The power of a neural network can be assessed on the basis of the receiver operator curve (ROC) by integrating the area beneath the curve.  For particle physicists, however, the common coinage is the expected statistical significance of an hypothetical signal, so Whiteson &amp; co translate the performance of their networks into a discovery significance defined by a number of standard deviations.  Notionally, a shallow neural network working only with low-level variables would achieve a significance of 2.57&sigma;, while adding in the high-level variables increases the significance to 3.02&sigma;.  In contrast, the deep neural networks achieve 3.16&sigma; with low-level, and 3.37&sigma; with all variables.</p>
<p>Some conclusions are obvious: deep is better than shallow.  Also, adding in the high-level variables helps in both cases.  (Whiteson et al. point out that the high-level variables incorporate the &tau; mass, which otherwise is unavailable to the neural networks.)  The deep network with low-level variables is better than a shallow network with all variables, and the authors conclude that the deep artificial neural network is learning something that is not embodied in the human-inspired high-level variables.   I am not convinced of this claim since it is not clear to me that the improvement is not simply due to the inadequacy of the shallow network to the task.   By way of an analogy, if we needed to approximate an exponential curve by a linear one, we would not succeed unless the range was very limited; we should not be surprised if a quadratic approximation is better.  </p>
<p>In any case, since I am working on similar things, I find this article very interesting.  It is clear that the field is moving in the direction of very advanced numerical techniques, and this is one fruitful direction to go in.</p>

	<p class="info">	<em class="date"><a href="https://muon.wordpress.com/2014/10/19/enhanced-higgs-to-tautau-search-with-deep-learning/" title="8:19 am" rel="bookmark">October 19, 2014 at 8:19 am</a></em>				<em class="comments-popup">
		<a href="https://muon.wordpress.com/2014/10/19/enhanced-higgs-to-tautau-search-with-deep-learning/#comments" class="commentlink" >2 comments</a>		</em>
			</p>

</div>

	
<div id="post-1385" class="entry post-1385 post type-post status-publish format-standard hentry category-particle-physics">

	<h2><a href="https://muon.wordpress.com/2014/10/12/neural-networks-for-triggering/">Neural Networks for&nbsp;Triggering</a></h2>

	<p>As experiments push the high-energy frontier, and also the intensity frontier, they must contend with higher and higher instantaneous luminosities.  This challenge drives experimenters to try new techniques for triggering that might have sounded outlandish or fanciful ten years ago.  </p>
<p>The Belle II experiment posted a paper this week on using (artificial) neural networks at the first trigger level for their experiment (<a href="http://arxiv.org/abs/1410.1395">arXiv:1410.1395</a>).  To be explicit: they plan to implement an artificial neural network at the hardware-trigger level, L1, i.e., the one that deals with the most primitive information from the detector in real time.  The L1 latency is 5 &mu;s which allows only 1 &mu;s for the trigger decision.</p>
<p>At issue is a major background coming from Touschek scattering.  The coulomb interaction of the e- and e+ beams can transform a small transverse phase space into a long longitudinal phase space.  (See a <a href="http://arxiv.org/abs/physics/9903034">DESY report 98-179</a> for a discussion.)  The beam is thereby spread out in the z direction leading to collisions taking place far from the center of the apparatus.  This is a bad thing for analysis and for triggering since much of the event remains unreconstructed &#8212; such events are a waste of bandwidth.  The artificial neural networks, once trained, are mechanistic and parallel in the way they do their calculations, therefore they are fast &#8211; just what is needed for this situation.  The interesting point is that here, in the Belle application, decisions about the z position of the vertex will be made without reconstructing any tracks (because there is insufficient time to carry out the reconstruction). </p>
<p>The CDC has 56 axial and stereo layers grouped into nine superlayers.  Track segments are found by the TSF based on superlayer information.  The 2D trigger module finds crude tracks in the (r,&phi;) plane.  The proposed neutral network trigger takes information from the axial and stereo TSF, and also from the 2D trigger module.</p>
<div data-shortcode="caption" id="attachment_1389" style="width: 579px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/10/belle-trigger.png"><img aria-describedby="caption-attachment-1389" data-attachment-id="1389" data-permalink="https://muon.wordpress.com/2014/10/12/neural-networks-for-triggering/belle-trigger/" data-orig-file="https://muon.files.wordpress.com/2014/10/belle-trigger.png" data-orig-size="569,242" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Belle-trigger" data-image-description="" data-image-caption="&lt;p&gt;Diagram of the Belle trigger. &lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/belle-trigger.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/10/belle-trigger.png?w=455" src="https://muon.files.wordpress.com/2014/10/belle-trigger.png?w=455" alt="Diagram of the Belle trigger. "   class="size-full wp-image-1389" srcset="https://muon.files.wordpress.com/2014/10/belle-trigger.png?w=455 455w, https://muon.files.wordpress.com/2014/10/belle-trigger.png?w=150 150w, https://muon.files.wordpress.com/2014/10/belle-trigger.png?w=300 300w, https://muon.files.wordpress.com/2014/10/belle-trigger.png 569w" sizes="(max-width: 455px) 100vw, 455px" /></a><p id="caption-attachment-1389" class="wp-caption-text">Diagram of the Belle trigger.</p></div>
<p>As usual, the artificial neural network is based on the multi-layer perceptron (MLP) with a hyperbolic tangent activation function.  The network is trained by back-propagation.  Interestingly, the authors use an ensemble of &#8220;expert&#8221; MLPs corresponding to small sectors in phase space.  Each MLP is trained on a subset of tracks corresponding to that sector.  Several incarnations of the network were investigated, which differ in the precise information used as input to the neural network. The drift times are scaled and the left/right/undecided information is represented by an integer.  The azimuthal angle can be represented by a scaled wire ID or by an angle relative to the one produced by the 2D trigger.  There is a linear relation between the arc length and the z coordinate, so the arc length (&mu;) can also be a useful input variable.</p>
<p>As a first test, one sector is trained for a sample of low-pT and another sample of high-pT tracks.  The parameter range is very constrained, and the artificial neural networks do well, achieving a resolution of 1.1 &#8211; 1.8 cm.  </p>
<p>In a second test, closer to the planned implementation, the output of the 2D trigger is represented by some smeared &phi; and pT values.  The track parameters cover a wider range than in the first test, and the pT range is divided into nine pieces.  The precision is 3 &#8211; 7cm in z, which is not yet good enough for the application (they are aiming for 2 cm or better).  Nonetheless, this estimate is useful because it can be used to restrict the sector size for the next step.</p>
<div data-shortcode="caption" id="attachment_1390" style="width: 431px" class="wp-caption alignnone"><a href="https://muon.files.wordpress.com/2014/10/belle-trigger-resolution.png"><img aria-describedby="caption-attachment-1390" data-attachment-id="1390" data-permalink="https://muon.wordpress.com/2014/10/12/neural-networks-for-triggering/belle-trigger-resolution/" data-orig-file="https://muon.files.wordpress.com/2014/10/belle-trigger-resolution.png" data-orig-size="421,264" data-comments-opened="1" data-image-meta="{&quot;aperture&quot;:&quot;0&quot;,&quot;credit&quot;:&quot;&quot;,&quot;camera&quot;:&quot;&quot;,&quot;caption&quot;:&quot;&quot;,&quot;created_timestamp&quot;:&quot;0&quot;,&quot;copyright&quot;:&quot;&quot;,&quot;focal_length&quot;:&quot;0&quot;,&quot;iso&quot;:&quot;0&quot;,&quot;shutter_speed&quot;:&quot;0&quot;,&quot;title&quot;:&quot;&quot;,&quot;orientation&quot;:&quot;0&quot;}" data-image-title="Belle-trigger-resolution" data-image-description="" data-image-caption="&lt;p&gt;Resolution on z versus curvature, for three versions of the neural network.&lt;/p&gt;
" data-medium-file="https://muon.files.wordpress.com/2014/10/belle-trigger-resolution.png?w=300" data-large-file="https://muon.files.wordpress.com/2014/10/belle-trigger-resolution.png?w=421" src="https://muon.files.wordpress.com/2014/10/belle-trigger-resolution.png?w=455" alt="Resolution on z versus curvature, for three versions of the neural network."   class="size-full wp-image-1390" srcset="https://muon.files.wordpress.com/2014/10/belle-trigger-resolution.png 421w, https://muon.files.wordpress.com/2014/10/belle-trigger-resolution.png?w=150 150w, https://muon.files.wordpress.com/2014/10/belle-trigger-resolution.png?w=300 300w" sizes="(max-width: 421px) 100vw, 421px" /></a><p id="caption-attachment-1390" class="wp-caption-text">Resolution on z versus curvature, for three versions of the neural network.</p></div>
<p>Clearly this is a work in progress, and much remains to be done.  Assuming that the Belle Collaboration succeeds, the fully pipelined neural network trigger will be realized on FPGA boards.</p>

	<p class="info">	<em class="date"><a href="https://muon.wordpress.com/2014/10/12/neural-networks-for-triggering/" title="2:16 pm" rel="bookmark">October 12, 2014 at 2:16 pm</a></em>				<em class="comments-popup">
		<a href="https://muon.wordpress.com/2014/10/12/neural-networks-for-triggering/#respond" class="commentlink" >Leave a comment</a>		</em>
			</p>

</div>
</div>